drop table if exists Person;

create table Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username varchar(100) NOT NULL,
                       year_of_birth int,
                       password varchar,
                       role varchar
);

truncate table Person;

insert into Person(username, year_of_birth, password, role)
VALUES ('vadim', 1973, '$2a$10$Y1D4pH6lbvuS35DXnUSGPuYmrTjtZxXPifRr97nMtU2BQ.bwnMo0G', 'ROLE_ADMIN'),
       ('elena', 1976, '$2a$10$Y1D4pH6lbvuS35DXnUSGPuYmrTjtZxXPifRr97nMtU2BQ.bwnMo0G', 'ROLE_USER'),
       ('kirill', 1974, '$2a$10$Y1D4pH6lbvuS35DXnUSGPuYmrTjtZxXPifRr97nMtU2BQ.bwnMo0G', 'ROLE_USER'),
       ('sergey', 1982, '$2a$10$Y1D4pH6lbvuS35DXnUSGPuYmrTjtZxXPifRr97nMtU2BQ.bwnMo0G', 'ROLE_USER');

select * from Person;